[MIG]port cagnotte modules to V10.0
acsone/acsone-addons pull request #141
Opened 2017-05-24 10:03 UTC by Cedric-Pigeon

2017-06-02 08:29 UTC, rousseldenis requested changes
Code review, Seems pretty good to me

2017-06-02 08:29 UTC, rousseldenis commented on cagnotte_base/models/cagnotte.py
> +    @api.multi
@Cedric-Pigeon Careful, this must be api.model

2017-06-02 08:51 UTC, JonathanNEMRY commented on cagnotte_base/__manifest__.py
> +        "security/cagnotte_base_security.xml",
more preferable to load security before case of using some groups into views

2017-06-02 08:51 UTC, JonathanNEMRY commented on cagnotte_base/demo/account_cagnotte_demo.xml
> +<openerp>
you can rename this one into odoo

2017-06-02 08:51 UTC, JonathanNEMRY commented on cagnotte_base/demo/account_cagnotte_demo.xml
> +    <data>
and remove this one if it is not a noupdate record

2017-06-02 08:51 UTC, JonathanNEMRY commented on cagnotte_base/models/cagnotte.py
> +
please add a _description

2017-06-02 08:51 UTC, JonathanNEMRY commented on cagnotte_base/demo/account_cagnotte_demo.xml
> +<openerp>
odoo

2017-06-02 08:51 UTC, JonathanNEMRY commented on cagnotte_coupon/models/cagnotte.py
> +                res.sudo().coupon_code = self.generate_coupon_code(res.id)
why sudo required here? is the create action triggered by someone that has not  write access?

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_base/models/cagnotte.py
> +            cagnotte.solde_cagnotte = solde_cagnotte
@Cedric-Pigeon Performances would be better with a read_group.

```python
        @api.multi
        @api.depends('account_move_line_ids.debit',
                                 'account_move_line_ids.credit')
        def _compute_solde_cagnotte(self):
        aml_model = self.env['account.move.line']
        domain = [
            ('account_cagnotte_id', 'in', self.ids)]

        res = aml_model.read_group(
            domain=domain,
            fields=['account_cagnotte_id', 'credit', 'debit'],
            groupby=['account_cagnotte_id']
        )

        aml_dict = {}
        for dic in res:
            cagnotte_id = dic['account_cagnotte_id'][0]
            solde_cagnotte = dic['credit'] - dic['debit']
            aml_dict[cagnotte_id] = solde_cagnotte

        for cagnotte in self:
            cagnotte.solde_cagnotte = aml_dict.get(cagnotte.id, 0.0)
```

But `solde_cagnotte` is stored so no big deal I guess...

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_base/models/cagnotte.py
> +        return True
@Cedric-Pigeon That could be written:

```python
@api.multi
def _check_cagnotte_account(self):
 """ Account must correspond to cagnotte account
 """
     return not any(l.account_cagnotte_id and l.account_cagnotte_id.cagnotte_type_id.account_id != l.account_id for l in self)
```

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_base/models/cagnotte.py
> +            self.account_id = self.cagnotte_type_id.account_id.id
@Cedric-Pigeon `.id` is not useful

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_base/tests/data/account_cagnotte_data.xml
> +</odoo>
@Cedric-Pigeon Newline :scream:

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_partner/views/cagnotte_views.xml
> +                <xpath expr="//div[@name='button_box']" position="inside">
@Cedric-Pigeon Could be written:

```xml
<div name="button_box" position="inside">
```

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_base/models/cagnotte.py
> +    _constraints = [
@Cedric-Pigeon Should be replaced by `@api.constrains`

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_base/models/cagnotte.py
> +            if values.get('account_id') and values.get('credit', 0) > 0:
@Cedric-Pigeon `credit` is a float and should be compared with `float_compare`.

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_base/models/cagnotte.py
> +    _constraints = [
@Cedric-Pigeon Should be replaced by `@api.constrains` and a `validationError` in the method.

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_partner/models/cagnotte.py
> +    _constraints = [
@Cedric-Pigeon `@api.constrains`

2017-06-02 09:27 UTC, ThomasBinsfeld commented on cagnotte_partner/models/cagnotte.py
> +            self.partner_id = self.account_cagnotte_id.partner_id.id
@Cedric-Pigeon `.id` is not useful

2017-06-06 07:51 UTC, ThomasBinsfeld commented on cagnotte_base/models/cagnotte.py
> +from openerp.exceptions import ValidationError
@Cedric-Pigeon  s/openerp/odoo

2017-06-06 08:02 UTC, Cedric-Pigeon commented
@JonathanNEMRY @rousseldenis @ThomasBinsfeld Code fixed following your reviews

2017-06-12 07:03 UTC, benwillig commented on cagnotte_coupon/models/cagnotte.py
> +    def create(self, vals):
multi decorator for a create method ?

2020-04-09 07:45 UTC, rousseldenis commented
Isn't it time to switch those modules there https://github.com/OCA/account-payment ?

@sbidoul @Cedric-Pigeon What do you think?

2020-04-09 08:13 UTC, sbidoul commented
@rousseldenis @Cedric-Pigeon the prerequisite to move this to OCA would be a good README that explain what these module do?

2020-04-09 08:22 UTC, rousseldenis commented
> @rousseldenis @Cedric-Pigeon the prerequisite to move this to OCA would be a good README that explain what these module do?

Indeed, this is at this time just an idea as I'm working with those modules and thought about letting them live their life on OCA (and maybe be migrated to other versions by others :-) )

2021-05-10 14:04 UTC, rousseldenis commented
Superseed through #147

2021-05-10 14:04 UTC, closed without merging